<meta name="csrf-token" content="{{ csrf_token() }}">

<div style="max-width: 1200px; margin: 0 auto; padding: 2rem;">
    <div style="margin-bottom: 2rem;">
        <h1 style="font-size: 2rem; font-weight: bold; margin-bottom: 0.5rem;">{{ $county->name }}</h1>
        <a href="/counties" style="color: #3b82f6; text-decoration: none;">&larr; Back to Counties</a>
    </div>

    <div style="margin-bottom: 2rem;">
        <h2 style="font-size: 1.5rem; font-weight: 600; margin-bottom: 1rem;">Select a letter:</h2>
        <div id="alphabet-grid" style="display: grid; grid-template-columns: repeat(auto-fill, minmax(50px, 1fr)); gap: 0.5rem; max-width: 800px;">
            <!-- Letters will be generated by JavaScript -->
        </div>
    </div>

    <div id="cities-section" style="display: none;">
        <h2 style="font-size: 1.5rem; font-weight: 600; margin-bottom: 1rem;">
            Cities starting with <span id="selected-letter"></span>:
        </h2>
        <p id="cities-loading" style="display: none;">Loading cities...</p>
        <p id="cities-error" style="color: #b91c1c; display: none;"></p>
        <ul id="cities-list" style="list-style: none; padding: 0; margin: 0; display: grid; grid-template-columns: repeat(auto-fill, minmax(250px, 1fr)); gap: 0.75rem;">
            <!-- Cities will be populated here -->
        </ul>
    </div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        const countyName = '{{ $county->name }}';
        const apiToken = '{{ session("api_token") }}';
        
        const alphabetGrid = document.getElementById('alphabet-grid');
        const citiesSection = document.getElementById('cities-section');
        const selectedLetterEl = document.getElementById('selected-letter');
        const citiesLoadingEl = document.getElementById('cities-loading');
        const citiesErrorEl = document.getElementById('cities-error');
        const citiesListEl = document.getElementById('cities-list');

        // Generate alphabet buttons (A-Z)
        const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('');
        alphabet.forEach(letter => {
            const button = document.createElement('button');
            button.textContent = letter;
            button.style.fontSize = '1.25rem';
            button.style.fontWeight = '600';
            button.style.backgroundColor = '#ffffff';
            button.style.cursor = 'pointer';


   
            button.addEventListener('click', function() {
                loadCitiesByLetter(letter);
                
            });

            alphabetGrid.appendChild(button);
        });

        function loadCitiesByLetter(letter) {
            selectedLetterEl.textContent = letter;
            citiesSection.style.display = 'block';
            citiesLoadingEl.style.display = 'block';
            citiesErrorEl.style.display = 'none';
            citiesListEl.innerHTML = '';

            fetch(`http://127.0.0.1:8000/api/county/{{$county->name}}/${letter}`, {
                method: 'GET',
                headers: {
                    'Content-Type': 'application/json',
                    'Accept': 'application/json',
                }
            })
            .then(response => {
                if (!response.ok) throw new Error('Network response was not ok: ' + response.status+' ' + response.statusText);
                return response.json();
            })
            .then(cities => {
                citiesLoadingEl.style.display = 'none';

                if (cities.error) {
                    citiesErrorEl.textContent = cities.error;
                    citiesErrorEl.style.display = 'block';
                    return;
                }

                if (!Array.isArray(cities) || cities.length === 0) {
                    citiesErrorEl.textContent = 'No cities found starting with ' + letter;
                    citiesErrorEl.style.display = 'block';
                    return;
                }

                citiesListEl.innerHTML = '';
                cities.forEach(city => {
                    const nameEl = document.createElement('div');
                    nameEl.textContent = city.city;
                    
                    citiesListEl.appendChild(nameEl);
                });
            })
            .catch(err => {
                console.error('Error fetching cities:', err);
                citiesLoadingEl.style.display = 'none';
                citiesErrorEl.textContent = 'Error fetching cities. See console for details.';
                citiesErrorEl.style.display = 'block';
            });
        }
    });
</script>
